import { useState } from 'react'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import MoreVertRoundedIcon from '@mui/icons-material/MoreVertRounded'
import { Alert, Button, Card, IconButton, Menu, MenuItem, Snackbar, Stack, TableCell, TableRow, TextField } from '@mui/material'
import { useNavigate } from 'react-router-dom'
import ConfirmDialog from '../../components/common/ConfirmDialog'
import ContentState from '../../components/common/ContentState'
import FormDrawer from '../../components/common/FormDrawer'
import FormSection from '../../components/common/FormSection'
import PageHeader from '../../components/common/PageHeader'
import PaginatedTable from '../../components/common/PaginatedTable'
import HourlyCostSection from '../../components/common/HourlyCostSection'
import StatusChip from '../../components/common/StatusChip'
import { useCollection } from '../../hooks/useCollection'
import { createRecord, deleteRecord, updateRecord } from '../../services/firestoreService'
import { formatDate } from '../../utils/formatters'

const blank = { company: 'Onshore', employeeId: '', employeeName: '', subProjectDocumentId: '', subProjectId: '', subProjectName: '', projectCategoryId: '', projectCategoryName: '', projectDocumentId: '', projectId: '', projectName: '', budgeted: 'Billable', rollOnDate: '', rollOffDate: '', dateOfJoining: '', excelacomExperience: '', finalCustomer: '', ctc: '', perHourCostDetails: [{ date: '', perHourCost: '' }], status: 'Active' }
const readOnlySx = { '& .MuiOutlinedInput-root': { bgcolor: '#F3F4F6' } }
function EmployeeMasterPage() {
  const employees = useCollection('employees'), subs = useCollection('subProjects'), navigate = useNavigate()
  const [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [anchor, setAnchor] = useState(null), [selected, setSelected] = useState(null)
  const activeSubs = subs.data.filter((item) => String(item.status).toLowerCase() === 'active')
  const hydrate = (documentId, source = form) => { const sub = subs.data.find((item) => item.id === documentId); return { ...source, subProjectDocumentId: sub?.id || '', subProjectId: sub?.subProjectId || '', subProjectName: sub?.subProjectName || '', projectCategoryId: sub?.projectCategoryId || '', projectCategoryName: sub?.projectCategoryName || '', projectDocumentId: sub?.projectDocumentId || '', projectId: sub?.projectId || '', projectName: sub?.projectName || '', rollOnDate: sub?.projectRollOnDate || '', rollOffDate: sub?.projectRollOffDate || '' } }
  const start = (item = null) => { if (!item && !activeSubs.length) { setNotice('Create a Sub Project before creating an Employee.'); return } setEditing(item); setForm(item ? { ...blank, ...item, ctc: item.ctc ?? '', perHourCostDetails: item.perHourCostDetails?.length ? item.perHourCostDetails : [{ date: '', perHourCost: '' }], subProjectDocumentId: item.subProjectDocumentId || subs.data.find((sub) => sub.subProjectId === item.subProjectId)?.id || '' } : { ...blank, perHourCostDetails: [{ date: '', perHourCost: '' }] }); setError(''); setOpen(true); setAnchor(null); setSelected(null) }
  const save = async (event) => { event.preventDefault(); const experience = Number(form.excelacomExperience); if (!form.company || !form.employeeId.trim() || !form.employeeName.trim() || !form.subProjectDocumentId || !form.budgeted || !form.dateOfJoining) return setError('Company, Employee ID, Employee Name, Sub Project, Budgeted and Date of Joining are required.'); if (!form.perHourCostDetails?.length || form.perHourCostDetails.some((detail) => !detail.date || detail.perHourCost === '' || !Number.isFinite(Number(detail.perHourCost)) || Number(detail.perHourCost) < 0)) return setError('Date and Per Hour Cost are required for every cost row.'); if (form.excelacomExperience !== '' && (!Number.isFinite(experience) || experience < 0)) return setError('Excelacom Experience must be a number greater than or equal to 0.'); if (employees.data.some((item) => item.id !== editing?.id && item.employeeId.toLowerCase() === form.employeeId.trim().toLowerCase())) return setError('Employee ID already exists.'); const payload = { ...hydrate(form.subProjectDocumentId, form), employeeId: form.employeeId.trim(), employeeName: form.employeeName.trim(), excelacomExperience: form.excelacomExperience === '' ? 0 : experience, finalCustomer: form.finalCustomer.trim() }; setSaving(true); try { if (editing) await updateRecord('employees', editing.id, payload); else await createRecord('employees', payload); setOpen(false); setNotice(editing ? 'Employee updated.' : 'Employee created.') } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const remove = async () => { setSaving(true); try { await deleteRecord('employees', selected.id); setSelected(null); setNotice('Employee deleted.') } catch (requestError) { setNotice(requestError.message) } finally { setSaving(false) } }
  return <Stack spacing={3}><PageHeader section="Masters / Employee Master" title="Employee Master" description="Manage employees and their project allocations." secondaryLabel="Import Excel" onSecondary={() => navigate('/imports/employees')} primaryLabel="Add Employee" primaryIcon={<AddRoundedIcon />} onPrimary={() => start()} />
    {!activeSubs.length && !subs.loading && <Alert severity="warning" action={<Button color="inherit" onClick={() => navigate('/masters/sub-projects')}>Create Sub Project</Button>}>Create a Sub Project before creating an Employee.</Alert>}
    <Card variant="outlined">{employees.loading || employees.error || !employees.data.length ? <ContentState loading={employees.loading} error={employees.error} title="No employees found" description="Create an employee after setting up the master hierarchy." /> : <PaginatedTable minWidth={1700} columns={['Company','Employee ID','Employee Name','Sub Project','Project','Project Category','Budgeted','Roll On','Roll Off','DOJ','Excelacom Experience','Final Customer','Status'].map((label) => ({ label })).concat({ label: 'Actions', align: 'right' })} rows={employees.data} renderRow={(item) => <TableRow hover key={item.id}><TableCell>{item.company}</TableCell><TableCell>{item.employeeId}</TableCell><TableCell>{item.employeeName}</TableCell><TableCell>{item.subProjectId} — {item.subProjectName}</TableCell><TableCell>{item.projectId} — {item.projectName}</TableCell><TableCell>{item.projectCategoryName}</TableCell><TableCell>{item.budgeted}</TableCell><TableCell>{formatDate(item.rollOnDate)}</TableCell><TableCell>{formatDate(item.rollOffDate)}</TableCell><TableCell>{formatDate(item.dateOfJoining)}</TableCell><TableCell>{item.excelacomExperience ?? item.experience ?? '—'}</TableCell><TableCell>{item.finalCustomer || '—'}</TableCell><TableCell><StatusChip status={item.status} /></TableCell><TableCell align="right"><IconButton onClick={(event) => { setAnchor(event.currentTarget); setSelected(item) }}><MoreVertRoundedIcon /></IconButton></TableCell></TableRow>} />}</Card>
    <Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => { setAnchor(null); setSelected(null) }}><MenuItem onClick={() => start(selected)}>Edit</MenuItem><MenuItem sx={{ color: 'error.main' }} onClick={() => setAnchor(null)}>Delete</MenuItem></Menu>
    <FormDrawer open={open} onClose={() => setOpen(false)} title={editing ? 'Edit Employee' : 'Add Employee'} subtitle="Employee profile and master allocation" onSubmit={save} saving={saving} submitLabel={editing ? 'Update Employee' : 'Create Employee'} width={800} mobileFullScreen>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack spacing={3}>
      <FormSection title="Employee Information" columns={2}><TextField select required label="Company" value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })}><MenuItem value="Onshore">Onshore</MenuItem><MenuItem value="Offshore">Offshore</MenuItem></TextField><TextField required label="Employee ID" value={form.employeeId} onChange={(event) => setForm({ ...form, employeeId: event.target.value })} /><TextField required label="Employee Name" value={form.employeeName} onChange={(event) => setForm({ ...form, employeeName: event.target.value })} /><TextField required type="date" label="Date of Joining" value={form.dateOfJoining} onChange={(event) => setForm({ ...form, dateOfJoining: event.target.value })} slotProps={{ inputLabel: { shrink: true } }} /><TextField type="number" label="Excelacom Experience" value={form.excelacomExperience} onChange={(event) => setForm({ ...form, excelacomExperience: event.target.value })} slotProps={{ htmlInput: { min: 0, step: '0.01' } }} /><TextField label="Final Customer" value={form.finalCustomer} onChange={(event) => setForm({ ...form, finalCustomer: event.target.value })} /></FormSection>
      <FormSection title="Project Allocation" divider columns={2}><TextField select required label="Sub Project Name" value={form.subProjectDocumentId} onChange={(event) => setForm(hydrate(event.target.value))}>{subs.data.filter((item) => item.id === form.subProjectDocumentId || String(item.status).toLowerCase() === 'active').map((item) => <MenuItem key={item.id} value={item.id}>{item.subProjectId} — {item.subProjectName}</MenuItem>)}</TextField><TextField select required label="Budgeted" value={form.budgeted} onChange={(event) => setForm({ ...form, budgeted: event.target.value })}><MenuItem value="Billable">Billable</MenuItem><MenuItem value="Non-Billable">Non-Billable</MenuItem></TextField><TextField label="Sub Project ID" value={form.subProjectId} sx={readOnlySx} slotProps={{ input: { readOnly: true } }} /><TextField label="Project Category" value={form.projectCategoryName} sx={readOnlySx} slotProps={{ input: { readOnly: true } }} /><TextField label="Project ID" value={form.projectId} sx={readOnlySx} slotProps={{ input: { readOnly: true } }} /><TextField label="Project Name" value={form.projectName} sx={readOnlySx} slotProps={{ input: { readOnly: true } }} /><TextField type="date" label="Roll On Date" value={form.rollOnDate} sx={readOnlySx} slotProps={{ input: { readOnly: true }, inputLabel: { shrink: true } }} /><TextField type="date" label="Roll Off Date" value={form.rollOffDate} sx={readOnlySx} slotProps={{ input: { readOnly: true }, inputLabel: { shrink: true } }} /></FormSection>
      <FormSection title="Compensation" divider columns={2}><TextField type="number" label="CTC" value={form.ctc} onChange={(event) => setForm({ ...form, ctc: event.target.value === '' ? '' : Number(event.target.value) })} slotProps={{ htmlInput: { min: 0, step: '0.01' } }} /></FormSection>
      <HourlyCostSection value={form.perHourCostDetails} onChange={(perHourCostDetails) => setForm({ ...form, perHourCostDetails })} />
    </Stack></FormDrawer>
    <ConfirmDialog open={Boolean(selected && !anchor)} title="Delete Employee?" description="Are you sure you want to delete this employee?" onCancel={() => setSelected(null)} onConfirm={remove} busy={saving} /><Snackbar open={Boolean(notice)} autoHideDuration={5000} onClose={() => setNotice('')}><Alert severity="info">{notice}</Alert></Snackbar>
  </Stack>
}
export default EmployeeMasterPage
