import { useMemo, useState } from 'react'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import MoreVertRoundedIcon from '@mui/icons-material/MoreVertRounded'
import SearchRoundedIcon from '@mui/icons-material/SearchRounded'
import { Alert, Avatar, Box, Card, IconButton, InputAdornment, Menu, MenuItem, Snackbar, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { useNavigate } from 'react-router-dom'
import ConfirmDialog from '../../components/common/ConfirmDialog'
import ContentState from '../../components/common/ContentState'
import FormDrawer from '../../components/common/FormDrawer'
import FormSection from '../../components/common/FormSection'
import PageHeader from '../../components/common/PageHeader'
import StatusChip from '../../components/common/StatusChip'
import { useCollection } from '../../hooks/useCollection'
import { createRecord, deleteRecord, updateRecord } from '../../services/firestoreService'
import { formatDate } from '../../utils/formatters'

const blank = { employeeId:'', employeeName:'', email:'', dateOfJoining:'', experience:'', projectId:'', subProjectId:'', budgeted:'yes', rollOnDate:'', rollOffDate:'', status:'active', exitDate:'', finalCustomer:'' }

function EmployeeMasterPage() {
  const employees = useCollection('employees'), projects = useCollection('projects'), subProjects = useCollection('subProjects'), navigate = useNavigate()
  const [search,setSearch]=useState(''),[projectFilter,setProjectFilter]=useState(''),[subFilter,setSubFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[budgetFilter,setBudgetFilter]=useState('')
  const [form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[anchor,setAnchor]=useState(null),[selected,setSelected]=useState(null)
  const mappedSubs = subProjects.data.filter((item)=>item.projectId===form.projectId)
  const filtered=useMemo(()=>employees.data.filter((item)=>`${item.employeeId} ${item.employeeName} ${item.email}`.toLowerCase().includes(search.toLowerCase())&&(!projectFilter||item.projectId===projectFilter)&&(!subFilter||item.subProjectId===subFilter)&&(!statusFilter||item.status===statusFilter)&&(!budgetFilter||String(item.budgeted)===budgetFilter)),[employees.data,search,projectFilter,subFilter,statusFilter,budgetFilter])
  const active=employees.data.filter((item)=>String(item.status).toLowerCase()==='active'), billable=active.filter((item)=>['yes','true','billable'].includes(String(item.budgeted).toLowerCase())), rolling=active.filter((item)=>{const days=(new Date(item.rollOffDate)-new Date())/86400000;return days>=0&&days<=30})
  const start=(item=null)=>{setEditing(item);setForm(item?{...blank,...item}:blank);setError('');setOpen(true);setAnchor(null);setSelected(null)}
  const save=async(event)=>{event.preventDefault();if(!form.employeeId.trim()||!form.employeeName.trim()||!form.email.trim())return setError('Employee ID, name and email are required.');if(employees.data.some((item)=>item.id!==editing?.id&&String(item.employeeId).toLowerCase()===form.employeeId.trim().toLowerCase()))return setError('Employee ID already exists.');const project=projects.data.find((item)=>item.projectId===form.projectId),sub=subProjects.data.find((item)=>item.subProjectId===form.subProjectId&&item.projectId===form.projectId);if(form.projectId&&!project)return setError('Select a valid project.');if(form.subProjectId&&!sub)return setError('Select a sub project mapped to the selected project.');setSaving(true);try{const payload={...form,employeeId:form.employeeId.trim(),employeeName:form.employeeName.trim(),email:form.email.trim(),projectName:project?.projectName||'',subProjectName:sub?.subProjectName||''};if(editing)await updateRecord('employees',editing.id,payload);else await createRecord('employees',payload);setOpen(false);setNotice(editing?'Employee updated.':'Employee created.')}catch(requestError){setError(requestError.message)}finally{setSaving(false)}}
  const remove=async()=>{try{await deleteRecord('employees',selected.id);setSelected(null);setNotice('Employee deleted.')}catch(requestError){setNotice(requestError.message)}}
  const summary=[['All Employees',employees.data.length],['Active',active.length],['Billable',billable.length],['Rolling Off Soon',rolling.length]]
  return <Stack spacing={3}><PageHeader section="Workforce / Employees" title="Employee Master" description="Manage employee profiles and project allocations." secondaryLabel="Import Excel" onSecondary={()=>navigate('/imports/employees')} primaryLabel="Add Employee" primaryIcon={<AddRoundedIcon/>} onPrimary={()=>start()} />
    <Box sx={{display:'grid',gridTemplateColumns:{xs:'repeat(2,minmax(0,1fr))',md:'repeat(4,minmax(0,1fr))'},gap:2}}>{summary.map(([label,value])=><Card variant="outlined" key={label}><Box sx={{p:2.25}}><Typography variant="body2" color="text.secondary">{label}</Typography><Typography fontSize={28} fontWeight={700} sx={{mt:.5}}>{value}</Typography></Box></Card>)}</Box>
    <Card variant="outlined"><Stack direction={{xs:'column',md:'row'}} gap={1.25} sx={{p:2}}><TextField size="small" placeholder="Search employee" value={search} onChange={(e)=>setSearch(e.target.value)} sx={{minWidth:{md:240},flex:1}} slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchRoundedIcon fontSize="small"/></InputAdornment>}}}/><TextField size="small" select label="Project" value={projectFilter} onChange={(e)=>{setProjectFilter(e.target.value);setSubFilter('')}} sx={{minWidth:160}}><MenuItem value="">All</MenuItem>{projects.data.map((item)=><MenuItem key={item.id} value={item.projectId}>{item.projectName}</MenuItem>)}</TextField><TextField size="small" select label="Sub Project" value={subFilter} onChange={(e)=>setSubFilter(e.target.value)} sx={{minWidth:160}}><MenuItem value="">All</MenuItem>{subProjects.data.filter((item)=>!projectFilter||item.projectId===projectFilter).map((item)=><MenuItem key={item.id} value={item.subProjectId}>{item.subProjectName}</MenuItem>)}</TextField><TextField size="small" select label="Status" value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)} sx={{minWidth:120}}><MenuItem value="">All</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField><TextField size="small" select label="Budgeted" value={budgetFilter} onChange={(e)=>setBudgetFilter(e.target.value)} sx={{minWidth:120}}><MenuItem value="">All</MenuItem><MenuItem value="yes">Yes</MenuItem><MenuItem value="no">No</MenuItem></TextField></Stack>
      {employees.loading||employees.error||!filtered.length?<ContentState loading={employees.loading} error={employees.error} title="No employees found" description="Add an employee manually or import a validated Excel workbook." actionLabel="Add Employee" onAction={()=>start()}/>:<TableContainer><Table><TableHead><TableRow><TableCell>Employee</TableCell><TableCell>Employee ID</TableCell><TableCell>Project / Sub Project</TableCell><TableCell>Budgeted</TableCell><TableCell>Roll On</TableCell><TableCell>Roll Off</TableCell><TableCell>Experience</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{filtered.map((item)=><TableRow hover key={item.id}><TableCell><Stack direction="row" spacing={1.25} alignItems="center"><Avatar sx={{width:32,height:32,bgcolor:'primary.50',color:'primary.dark',fontSize:12}}>{item.employeeName?.split(' ').map((part)=>part[0]).join('').slice(0,2)}</Avatar><Box><Typography fontSize={13.5} fontWeight={600}>{item.employeeName}</Typography><Typography variant="caption" color="text.secondary">{item.email}</Typography></Box></Stack></TableCell><TableCell>{item.employeeId}</TableCell><TableCell><Typography fontSize={13}>{item.projectName||'—'}</Typography><Typography variant="caption" color="text.secondary">{item.subProjectName||'—'}</Typography></TableCell><TableCell>{item.budgeted||'—'}</TableCell><TableCell>{formatDate(item.rollOnDate)}</TableCell><TableCell>{formatDate(item.rollOffDate)}</TableCell><TableCell>{item.experience||'—'}</TableCell><TableCell><StatusChip status={item.status}/></TableCell><TableCell align="right"><IconButton onClick={(e)=>{setAnchor(e.currentTarget);setSelected(item)}}><MoreVertRoundedIcon/></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer>}</Card>
    <Menu anchorEl={anchor} open={Boolean(anchor)} onClose={()=>{setAnchor(null);setSelected(null)}}><MenuItem onClick={()=>start(selected)}>Edit</MenuItem><MenuItem sx={{color:'error.main'}} onClick={()=>setAnchor(null)}>Delete</MenuItem></Menu>
    <FormDrawer open={open} onClose={()=>setOpen(false)} title={editing?'Edit Employee':'Add Employee'} subtitle="Employee profile and allocation" onSubmit={save} saving={saving} submitLabel={editing?'Update Employee':'Create Employee'} width={840} mobileFullScreen>{error&&<Alert severity="error" variant="outlined" sx={{mb:2.5}}>{error}</Alert>}<Stack spacing={3}>{[['Basic Information',[['employeeId','Employee ID'],['employeeName','Employee Name'],['email','Email'],['dateOfJoining','Date of Joining','date'],['experience','Experience']]],['Project Allocation',[['projectId','Project','project'],['subProjectId','Sub Project','sub'],['budgeted','Budgeted','budget'],['rollOnDate','Roll On Date','date'],['rollOffDate','Roll Off Date','date']]],['Employment',[['status','Status','status'],['exitDate','Exit Date','date'],['finalCustomer','Final Customer']]]].map(([section,fields],index)=><FormSection key={section} title={section==='Employment'?'Employment Details':section} divider={index>0} columns={2}>{fields.map(([key,label,type])=>type==='project'?<TextField key={key} select label={label} value={form[key]} onChange={(e)=>setForm({...form,projectId:e.target.value,subProjectId:''})}><MenuItem value="">None</MenuItem>{projects.data.map((item)=><MenuItem key={item.id} value={item.projectId}>{item.projectId} — {item.projectName}</MenuItem>)}</TextField>:type==='sub'?<TextField key={key} select label={label} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})} disabled={!form.projectId}><MenuItem value="">None</MenuItem>{mappedSubs.map((item)=><MenuItem key={item.id} value={item.subProjectId}>{item.subProjectId} — {item.subProjectName}</MenuItem>)}</TextField>:type==='budget'?<TextField key={key} select label={label} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}><MenuItem value="yes">Yes</MenuItem><MenuItem value="no">No</MenuItem></TextField>:type==='status'?<TextField key={key} select label={label} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField>:<TextField key={key} label={label} type={type||'text'} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})} slotProps={type==='date'?{inputLabel:{shrink:true}}:undefined}/>)}</FormSection>)}</Stack></FormDrawer>
    <ConfirmDialog open={Boolean(selected&&!anchor)} title="Delete employee?" description={`Delete ${selected?.employeeName||'this employee'}?`} onCancel={()=>setSelected(null)} onConfirm={remove}/><Snackbar open={Boolean(notice)} autoHideDuration={5000} onClose={()=>setNotice('')}><Alert severity="info">{notice}</Alert></Snackbar>
  </Stack>
}

export default EmployeeMasterPage
