import { useState } from 'react'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import MoreVertRoundedIcon from '@mui/icons-material/MoreVertRounded'
import { Alert, Card, IconButton, Menu, MenuItem, Snackbar, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField } from '@mui/material'
import ConfirmDialog from '../../components/common/ConfirmDialog'
import ContentState from '../../components/common/ContentState'
import FormDrawer from '../../components/common/FormDrawer'
import FormSection from '../../components/common/FormSection'
import PageHeader from '../../components/common/PageHeader'
import PaginatedTable from '../../components/common/PaginatedTable'
import StatusChip from '../../components/common/StatusChip'
import { useCollection } from '../../hooks/useCollection'
import { createRecord, deleteRecord, updateRecord } from '../../services/firestoreService'

const months = ['January','February','March','April','May','June','July','August','September','October','November','December']
const blank = { year: new Date().getFullYear(), month: new Date().getMonth() + 1, hours: '', actualHours: '', status: 'active' }

function ForecastMasterPage() {
  const forecasts = useCollection('forecastMasters')
  const [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [anchor, setAnchor] = useState(null), [selected, setSelected] = useState(null)
  const start = (item = null) => { setEditing(item); setForm(item ? { year: item.year, month: item.month, hours: item.hours ?? item.forecastHours, actualHours: item.actualHours || '', status: item.status || 'active' } : blank); setError(''); setOpen(true); setAnchor(null); setSelected(null) }
  const save = async (event) => { event.preventDefault(); const hours = Number(form.hours); if (!form.year || !form.month || !Number.isFinite(hours) || hours <= 0) return setError('Year, month and positive forecast hours are required.'); if (forecasts.data.some((item) => item.id !== editing?.id && Number(item.year) === Number(form.year) && Number(item.month) === Number(form.month))) return setError('A forecast already exists for this year and month.'); setSaving(true); try { const payload = { year: Number(form.year), month: Number(form.month), monthName: months[Number(form.month) - 1], hours, actualHours: Number(form.actualHours || 0), status: form.status }; if (editing) await updateRecord('forecastMasters', editing.id, payload); else await createRecord('forecastMasters', payload); setOpen(false); setNotice(editing ? 'Forecast updated.' : 'Forecast created.') } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const remove = async () => { try { await deleteRecord('forecastMasters', selected.id); setSelected(null); setNotice('Forecast deleted.') } catch (errorValue) { setNotice(errorValue.message) } }
  return <Stack spacing={3}><PageHeader section="Masters / Forecast Master" title="Forecast Master" description="Maintain monthly forecast hours and compare forecast against actuals." primaryLabel="Add Forecast" primaryIcon={<AddRoundedIcon />} onPrimary={() => start()} />
    <Card variant="outlined">{forecasts.loading || forecasts.error || !forecasts.data.length ? <ContentState loading={forecasts.loading} error={forecasts.error} title="No forecasts created yet" description="Add monthly forecast hours to begin utilization tracking." /> : <PaginatedTable columns={['Month','Forecast Hours','Actual Hours','Variance','Variance %','Status'].map((label) => ({ label })).concat({ label: 'Actions', align: 'right' })} rows={[...forecasts.data].sort((a,b) => a.year-b.year || a.month-b.month)} renderRow={(item) => { const fc = Number(item.hours ?? item.forecastHours ?? 0), ac = Number(item.actualHours || 0), variance = ac - fc; return <TableRow hover key={item.id}><TableCell>{months[item.month - 1]} {item.year}</TableCell><TableCell sx={{ color: 'secondary.main', fontWeight: 650 }}>FC: {fc}</TableCell><TableCell sx={{ color: 'primary.dark', fontWeight: 650 }}>AC: {ac}</TableCell><TableCell>{variance}</TableCell><TableCell>{fc ? `${((variance / fc) * 100).toFixed(1)}%` : '0%'}</TableCell><TableCell><StatusChip status={item.status} /></TableCell><TableCell align="right"><IconButton onClick={(event) => { setAnchor(event.currentTarget); setSelected(item) }}><MoreVertRoundedIcon /></IconButton></TableCell></TableRow> }} />}</Card>
    <Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => { setAnchor(null); setSelected(null) }}><MenuItem onClick={() => start(selected)}>Edit</MenuItem><MenuItem sx={{ color: 'error.main' }} onClick={() => setAnchor(null)}>Delete</MenuItem></Menu>
    <FormDrawer open={open} onClose={() => setOpen(false)} title={editing ? 'Edit Forecast' : 'New Forecast'} subtitle="Monthly forecast information" onSubmit={save} saving={saving} submitLabel={editing ? 'Update Forecast' : 'Create Forecast'} width={560}>{error && <Alert severity="error" variant="outlined" sx={{ mb: 2.5 }}>{error}</Alert>}<FormSection title="Forecast Information"><TextField select label="Year" value={form.year} onChange={(event) => setForm({ ...form, year: event.target.value })}>{Array.from({ length: 8 }, (_, index) => new Date().getFullYear() - 2 + index).map((year) => <MenuItem key={year} value={year}>{year}</MenuItem>)}</TextField><TextField select label="Month" value={form.month} onChange={(event) => setForm({ ...form, month: event.target.value })}>{months.map((month, index) => <MenuItem key={month} value={index + 1}>{month}</MenuItem>)}</TextField><TextField type="number" label="Forecast Hours" value={form.hours} onChange={(event) => setForm({ ...form, hours: event.target.value })} slotProps={{ htmlInput: { min: 1 } }} /><TextField type="number" label="Actual Hours" value={form.actualHours} onChange={(event) => setForm({ ...form, actualHours: event.target.value })} slotProps={{ htmlInput: { min: 0 } }} /><TextField select label="Status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField></FormSection></FormDrawer>
    <ConfirmDialog open={Boolean(selected && !anchor)} title="Delete forecast?" description="Delete this monthly forecast record?" onCancel={() => setSelected(null)} onConfirm={remove} /><Snackbar open={Boolean(notice)} autoHideDuration={5000} onClose={() => setNotice('')}><Alert severity="info">{notice}</Alert></Snackbar>
  </Stack>
}

export default ForecastMasterPage
