import { useState } from 'react'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import MoreVertRoundedIcon from '@mui/icons-material/MoreVertRounded'
import { Alert, Button, Card, IconButton, Menu, MenuItem, Snackbar, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField } from '@mui/material'
import { useNavigate } from 'react-router-dom'
import ConfirmDialog from '../../components/common/ConfirmDialog'
import ContentState from '../../components/common/ContentState'
import FormDrawer from '../../components/common/FormDrawer'
import FormSection from '../../components/common/FormSection'
import PageHeader from '../../components/common/PageHeader'
import PaginatedTable from '../../components/common/PaginatedTable'
import StatusChip from '../../components/common/StatusChip'
import { useCollection } from '../../hooks/useCollection'
import { createRecord, deleteRecord, updateRecord } from '../../services/firestoreService'
import { formatDate } from '../../utils/formatters'

const blank = { projectCategoryId: '', projectCategoryName: '', projectId: '', projectName: '', rollOnDate: '', rollOffDate: '', status: 'Active' }
function ProjectMasterPage() {
  const categories = useCollection('projectCategories'), projects = useCollection('projects'), subs = useCollection('subProjects'), employees = useCollection('employees'), navigate = useNavigate()
  const [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [anchor, setAnchor] = useState(null), [selected, setSelected] = useState(null)
  const activeCategories = categories.data.filter((item) => String(item.status).toLowerCase() === 'active')
  const start = (item = null) => { if (!item && !activeCategories.length) { setNotice('Create a Project Category before creating a Project.'); return } setEditing(item); setForm(item ? { ...blank, ...item } : blank); setError(''); setOpen(true); setAnchor(null); setSelected(null) }
  const save = async (event) => { event.preventDefault(); const category = categories.data.find((item) => item.id === form.projectCategoryId); if (!category || !form.projectId.trim() || !form.projectName.trim() || !form.rollOnDate || !form.rollOffDate) return setError('All fields are required.'); if (form.rollOffDate < form.rollOnDate) return setError('Roll Off Date cannot be before Roll On Date.'); if (projects.data.some((item) => item.id !== editing?.id && String(item.projectId).toLowerCase() === form.projectId.trim().toLowerCase())) return setError('Project ID already exists.'); setSaving(true); try { const payload = { ...form, projectCategoryName: category.name, projectId: form.projectId.trim(), projectName: form.projectName.trim() }; if (editing) { await updateRecord('projects', editing.id, payload); const child = { projectDocumentId: editing.id, projectId: payload.projectId, projectName: payload.projectName, projectCategoryId: payload.projectCategoryId, projectCategoryName: payload.projectCategoryName, projectRollOnDate: payload.rollOnDate, projectRollOffDate: payload.rollOffDate }; await Promise.all([...subs.data.filter((item) => item.projectDocumentId === editing.id || (!item.projectDocumentId && item.projectId === editing.projectId)).map((item) => updateRecord('subProjects', item.id, child)), ...employees.data.filter((item) => item.projectDocumentId === editing.id || (!item.projectDocumentId && item.projectId === editing.projectId)).map((item) => updateRecord('employees', item.id, { ...child, rollOnDate: payload.rollOnDate, rollOffDate: payload.rollOffDate }))]) } else await createRecord('projects', payload); setOpen(false); setNotice(editing ? 'Project updated.' : 'Project created.') } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const remove = async () => { if (subs.data.some((item) => item.projectDocumentId === selected.id || item.projectId === selected.projectId)) { setNotice('This project is currently mapped to one or more sub projects.'); setSelected(null); return } setSaving(true); try { await deleteRecord('projects', selected.id); setSelected(null); setNotice('Project deleted.') } catch (requestError) { setNotice(requestError.message) } finally { setSaving(false) } }
  return <Stack spacing={3}><PageHeader section="Masters / Project Master" title="Project Master" description="Manage projects used for employee allocation." primaryLabel="New Project" primaryIcon={<AddRoundedIcon />} onPrimary={() => start()} />
    {!activeCategories.length && !categories.loading && <Alert severity="warning" action={<Button color="inherit" onClick={() => navigate('/masters/project-categories')}>Create Category</Button>}>Create a Project Category before creating a Project.</Alert>}
    <Card variant="outlined">{projects.loading || projects.error || !projects.data.length ? <ContentState loading={projects.loading} error={projects.error} title="No projects created yet" description="Create a project after creating a project category." /> : <PaginatedTable columns={['Project Category','Project ID','Project Name','Roll On Date','Roll Off Date','Status'].map((label) => ({ label })).concat({ label: 'Actions', align: 'right' })} rows={projects.data} renderRow={(item) => <TableRow hover key={item.id}><TableCell>{item.projectCategoryName || '—'}</TableCell><TableCell>{item.projectId}</TableCell><TableCell>{item.projectName}</TableCell><TableCell>{formatDate(item.rollOnDate)}</TableCell><TableCell>{formatDate(item.rollOffDate)}</TableCell><TableCell><StatusChip status={item.status} /></TableCell><TableCell align="right"><IconButton onClick={(event) => { setAnchor(event.currentTarget); setSelected(item) }}><MoreVertRoundedIcon /></IconButton></TableCell></TableRow>} />}</Card>
    <Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => { setAnchor(null); setSelected(null) }}><MenuItem onClick={() => start(selected)}>Edit</MenuItem><MenuItem sx={{ color: 'error.main' }} onClick={() => setAnchor(null)}>Delete</MenuItem></Menu>
    <FormDrawer open={open} onClose={() => setOpen(false)} title={editing ? 'Edit Project' : 'New Project'} subtitle="Project master information" onSubmit={save} saving={saving} submitLabel={editing ? 'Update Project' : 'Create Project'}>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<FormSection title="Project Information"><TextField select required label="Project Category" value={form.projectCategoryId} onChange={(event) => setForm({ ...form, projectCategoryId: event.target.value })}>{categories.data.filter((item) => item.id === form.projectCategoryId || String(item.status).toLowerCase() === 'active').map((item) => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField><TextField required label="Project ID" value={form.projectId} onChange={(event) => setForm({ ...form, projectId: event.target.value })} /><TextField required label="Project Name" value={form.projectName} onChange={(event) => setForm({ ...form, projectName: event.target.value })} /><TextField required type="date" label="Roll On Date" value={form.rollOnDate} onChange={(event) => setForm({ ...form, rollOnDate: event.target.value })} slotProps={{ inputLabel: { shrink: true } }} /><TextField required type="date" label="Roll Off Date" value={form.rollOffDate} onChange={(event) => setForm({ ...form, rollOffDate: event.target.value })} slotProps={{ inputLabel: { shrink: true } }} /></FormSection></FormDrawer>
    <ConfirmDialog open={Boolean(selected && !anchor)} title="Delete Project?" description="Are you sure you want to delete this project?" onCancel={() => setSelected(null)} onConfirm={remove} busy={saving} /><Snackbar open={Boolean(notice)} autoHideDuration={5000} onClose={() => setNotice('')}><Alert severity="info">{notice}</Alert></Snackbar>
  </Stack>
}
export default ProjectMasterPage
