import { useState } from 'react'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import MoreVertRoundedIcon from '@mui/icons-material/MoreVertRounded'
import { Alert, Button, Card, IconButton, Menu, MenuItem, Snackbar, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField } from '@mui/material'
import { useNavigate } from 'react-router-dom'
import ConfirmDialog from '../../components/common/ConfirmDialog'
import ContentState from '../../components/common/ContentState'
import FormDrawer from '../../components/common/FormDrawer'
import FormSection from '../../components/common/FormSection'
import PageHeader from '../../components/common/PageHeader'
import PaginatedTable from '../../components/common/PaginatedTable'
import StatusChip from '../../components/common/StatusChip'
import { useCollection } from '../../hooks/useCollection'
import { createRecord, deleteRecord, updateRecord } from '../../services/firestoreService'

const blank = { subProjectId: '', subProjectName: '', projectDocumentId: '', status: 'Active' }
function SubProjectMasterPage() {
  const projects = useCollection('projects'), subs = useCollection('subProjects'), employees = useCollection('employees'), navigate = useNavigate()
  const [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [anchor, setAnchor] = useState(null), [selected, setSelected] = useState(null)
  const activeProjects = projects.data.filter((item) => String(item.status).toLowerCase() === 'active')
  const start = (item = null) => { if (!item && !activeProjects.length) { setNotice('Create a Project before creating a Sub Project.'); return } setEditing(item); setForm(item ? { ...blank, ...item, projectDocumentId: item.projectDocumentId || projects.data.find((project) => project.projectId === item.projectId)?.id || '' } : blank); setError(''); setOpen(true); setAnchor(null); setSelected(null) }
  const save = async (event) => { event.preventDefault(); const project = projects.data.find((item) => item.id === form.projectDocumentId); if (!project || !form.subProjectId.trim() || !form.subProjectName.trim()) return setError('All fields are required.'); if (subs.data.some((item) => item.id !== editing?.id && item.subProjectId.toLowerCase() === form.subProjectId.trim().toLowerCase())) return setError('Sub Project ID already exists.'); setSaving(true); try { const payload = { ...form, subProjectId: form.subProjectId.trim(), subProjectName: form.subProjectName.trim(), projectDocumentId: project.id, projectId: project.projectId, projectName: project.projectName, projectCategoryId: project.projectCategoryId, projectCategoryName: project.projectCategoryName, projectRollOnDate: project.rollOnDate, projectRollOffDate: project.rollOffDate }; if (editing) { await updateRecord('subProjects', editing.id, payload); await Promise.all(employees.data.filter((item) => item.subProjectDocumentId === editing.id || (!item.subProjectDocumentId && item.subProjectId === editing.subProjectId)).map((item) => updateRecord('employees', item.id, { subProjectDocumentId: editing.id, subProjectId: payload.subProjectId, subProjectName: payload.subProjectName, projectDocumentId: payload.projectDocumentId, projectId: payload.projectId, projectName: payload.projectName, projectCategoryId: payload.projectCategoryId, projectCategoryName: payload.projectCategoryName, rollOnDate: payload.projectRollOnDate, rollOffDate: payload.projectRollOffDate }))) } else await createRecord('subProjects', payload); setOpen(false); setNotice(editing ? 'Sub project updated.' : 'Sub project created.') } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const remove = async () => { if (employees.data.some((item) => item.subProjectDocumentId === selected.id || item.subProjectId === selected.subProjectId)) { setNotice('This sub project is currently assigned to one or more employees.'); setSelected(null); return } setSaving(true); try { await deleteRecord('subProjects', selected.id); setSelected(null); setNotice('Sub project deleted.') } catch (requestError) { setNotice(requestError.message) } finally { setSaving(false) } }
  return <Stack spacing={3}><PageHeader section="Masters / Sub Project Master" title="Sub Project Master" description="Manage sub projects and their main project relationships." primaryLabel="New Sub Project" primaryIcon={<AddRoundedIcon />} onPrimary={() => start()} />
    {!activeProjects.length && !projects.loading && <Alert severity="warning" action={<Button color="inherit" onClick={() => navigate('/masters/projects')}>Create Project</Button>}>Create a Project before creating a Sub Project.</Alert>}
    <Card variant="outlined">{subs.loading || subs.error || !subs.data.length ? <ContentState loading={subs.loading} error={subs.error} title="No sub projects created yet" description="Create a sub project after creating a project." /> : <PaginatedTable columns={['Sub Project ID','Sub Project Name','Main Project','Project Category','Status'].map((label) => ({ label })).concat({ label: 'Actions', align: 'right' })} rows={subs.data} renderRow={(item) => <TableRow hover key={item.id}><TableCell>{item.subProjectId}</TableCell><TableCell>{item.subProjectName}</TableCell><TableCell>{item.projectId} — {item.projectName}</TableCell><TableCell>{item.projectCategoryName || '—'}</TableCell><TableCell><StatusChip status={item.status} /></TableCell><TableCell align="right"><IconButton onClick={(event) => { setAnchor(event.currentTarget); setSelected(item) }}><MoreVertRoundedIcon /></IconButton></TableCell></TableRow>} />}</Card>
    <Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => { setAnchor(null); setSelected(null) }}><MenuItem onClick={() => start(selected)}>Edit</MenuItem><MenuItem sx={{ color: 'error.main' }} onClick={() => setAnchor(null)}>Delete</MenuItem></Menu>
    <FormDrawer open={open} onClose={() => setOpen(false)} title={editing ? 'Edit Sub Project' : 'New Sub Project'} subtitle="Sub project master information" onSubmit={save} saving={saving} submitLabel={editing ? 'Update Sub Project' : 'Create Sub Project'}>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<FormSection title="Sub Project Information"><TextField required label="Sub Project ID" value={form.subProjectId} onChange={(event) => setForm({ ...form, subProjectId: event.target.value })} /><TextField required label="Sub Project Name" value={form.subProjectName} onChange={(event) => setForm({ ...form, subProjectName: event.target.value })} /><TextField select required label="Main Project" value={form.projectDocumentId} onChange={(event) => setForm({ ...form, projectDocumentId: event.target.value })}>{projects.data.filter((item) => item.id === form.projectDocumentId || String(item.status).toLowerCase() === 'active').map((item) => <MenuItem key={item.id} value={item.id}>{item.projectId} — {item.projectName}</MenuItem>)}</TextField></FormSection></FormDrawer>
    <ConfirmDialog open={Boolean(selected && !anchor)} title="Delete Sub Project?" description="Are you sure you want to delete this sub project?" onCancel={() => setSelected(null)} onConfirm={remove} busy={saving} /><Snackbar open={Boolean(notice)} autoHideDuration={5000} onClose={() => setNotice('')}><Alert severity="info">{notice}</Alert></Snackbar>
  </Stack>
}
export default SubProjectMasterPage
