import { useMemo, useState } from 'react'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import MoreVertRoundedIcon from '@mui/icons-material/MoreVertRounded'
import SearchRoundedIcon from '@mui/icons-material/SearchRounded'
import { Alert, Box, Card, IconButton, InputAdornment, Menu, MenuItem, Snackbar, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField } from '@mui/material'
import ConfirmDialog from '../../components/common/ConfirmDialog'
import ContentState from '../../components/common/ContentState'
import FormDrawer from '../../components/common/FormDrawer'
import FormSection from '../../components/common/FormSection'
import PageHeader from '../../components/common/PageHeader'
import StatusChip from '../../components/common/StatusChip'
import { useCollection } from '../../hooks/useCollection'
import { createRecord, deleteRecord, updateRecord } from '../../services/firestoreService'
import { formatDate } from '../../utils/formatters'

const blank = { projectId: '', subProjectId: '', subProjectName: '', status: 'active' }

function SubProjectMasterPage() {
  const projects = useCollection('projects'), subProjects = useCollection('subProjects'), employees = useCollection('employees')
  const [search, setSearch] = useState(''), [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [anchor, setAnchor] = useState(null), [selected, setSelected] = useState(null), [confirming, setConfirming] = useState(false)
  const filtered = useMemo(() => subProjects.data.filter((item) => `${item.subProjectId} ${item.subProjectName} ${item.projectName}`.toLowerCase().includes(search.toLowerCase())), [subProjects.data, search])
  const openCreate = () => { setForm(blank); setEditing(null); setError(''); setOpen(true) }
  const openEdit = (item) => { setForm({ projectId: item.projectId, subProjectId: item.subProjectId, subProjectName: item.subProjectName, status: item.status || 'active' }); setEditing(item); setOpen(true); setAnchor(null); setSelected(null) }
  const save = async (event) => { event.preventDefault(); const project = projects.data.find((item) => item.projectId === form.projectId); if (!project || !form.subProjectId.trim() || !form.subProjectName.trim()) return setError('Project, Sub Project ID and Name are required.'); if (subProjects.data.some((item) => item.id !== editing?.id && String(item.subProjectId).toLowerCase() === form.subProjectId.trim().toLowerCase())) return setError('Sub Project ID already exists.'); setSaving(true); setError(''); try { const payload = { projectId: project.projectId, projectName: project.projectName, subProjectId: form.subProjectId.trim(), subProjectName: form.subProjectName.trim(), status: form.status }; if (editing) await updateRecord('subProjects', editing.id, payload); else await createRecord('subProjects', payload); setOpen(false); setNotice(editing ? 'Sub project updated.' : 'Sub project created.') } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const remove = async () => { if (employees.data.some((item) => item.subProjectId === selected.subProjectId)) { setNotice('Remove mapped employees before deleting this sub project.'); setSelected(null); return } setConfirming(true); try { await deleteRecord('subProjects', selected.id); setSelected(null); setNotice('Sub project deleted.') } catch (requestError) { setNotice(requestError.message) } finally { setConfirming(false) } }
  return <Stack spacing={3}><PageHeader section="Masters / Sub Project Master" title="Sub Project Master" description="Manage sub-projects and their parent project mappings." primaryLabel="New Sub Project" primaryIcon={<AddRoundedIcon />} onPrimary={openCreate} />
    <Card variant="outlined"><Box sx={{ p: 2 }}><TextField size="small" placeholder="Search sub projects" value={search} onChange={(event) => setSearch(event.target.value)} sx={{ width: { xs: '100%', sm: 340 } }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchRoundedIcon fontSize="small" /></InputAdornment> } }} /></Box>{subProjects.loading || subProjects.error || !filtered.length ? <ContentState loading={subProjects.loading} error={subProjects.error} title="No sub projects created yet" description="Create a sub project and map it to an active parent project." actionLabel="Create Sub Project" onAction={openCreate} /> : <TableContainer><Table><TableHead><TableRow><TableCell>Sub Project ID</TableCell><TableCell>Sub Project Name</TableCell><TableCell>Parent Project</TableCell><TableCell>Employees</TableCell><TableCell>Status</TableCell><TableCell>Updated</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{filtered.map((item) => <TableRow hover key={item.id}><TableCell>{item.subProjectId}</TableCell><TableCell>{item.subProjectName}</TableCell><TableCell>{item.projectId} — {item.projectName}</TableCell><TableCell>{employees.data.filter((employee) => employee.subProjectId === item.subProjectId).length}</TableCell><TableCell><StatusChip status={item.status} /></TableCell><TableCell>{formatDate(item.updatedAt)}</TableCell><TableCell align="right"><IconButton onClick={(event) => { setAnchor(event.currentTarget); setSelected(item) }}><MoreVertRoundedIcon /></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer>}</Card>
    <Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => { setAnchor(null); setSelected(null) }}><MenuItem onClick={() => openEdit(selected)}>Edit</MenuItem><MenuItem sx={{ color: 'error.main' }} onClick={() => setAnchor(null)}>Delete</MenuItem></Menu>
    <FormDrawer open={open} onClose={() => setOpen(false)} title={editing ? 'Edit Sub Project' : 'New Sub Project'} subtitle={editing ? 'Update the selected sub project record' : 'Create a new sub project master record'} onSubmit={save} saving={saving} submitLabel={editing ? 'Update Sub Project' : 'Create Sub Project'} width={580}>{error && <Alert severity="error" variant="outlined" sx={{ mb: 2.5 }}>{error}</Alert>}<FormSection title="Sub Project Information"><TextField select required label="Parent Project" value={form.projectId} onChange={(event) => setForm({ ...form, projectId: event.target.value })}>{projects.data.map((item) => <MenuItem key={item.id} value={item.projectId}>{item.projectId} — {item.projectName}</MenuItem>)}</TextField><TextField required label="Sub Project ID" value={form.subProjectId} onChange={(event) => setForm({ ...form, subProjectId: event.target.value })} /><TextField required label="Sub Project Name" value={form.subProjectName} onChange={(event) => setForm({ ...form, subProjectName: event.target.value })} /><TextField select label="Status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField></FormSection></FormDrawer>
    <ConfirmDialog open={Boolean(selected && !anchor)} title="Delete sub project?" description={`Delete ${selected?.subProjectName || 'this sub project'}?`} onCancel={() => setSelected(null)} onConfirm={remove} busy={confirming} /><Snackbar open={Boolean(notice)} autoHideDuration={5000} onClose={() => setNotice('')}><Alert severity="info">{notice}</Alert></Snackbar>
  </Stack>
}

export default SubProjectMasterPage
